// Auto-generated by LibreLane
module core_wrap(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk_i,
  input rst_ni,
  input test_enable_i,
  input[15:0] irqs_i,
  input timer_irq_i,
  input software_irq_i,
  input[31:0] boot_addr_i,
  output instr_req_o,
  input instr_gnt_i,
  input instr_rvalid_i,
  output[31:0] instr_addr_o,
  input[31:0] instr_rdata_i,
  input instr_err_i,
  output data_req_o,
  input data_gnt_i,
  input data_rvalid_i,
  output data_we_o,
  output[3:0] data_be_o,
  output[31:0] data_addr_o,
  output[31:0] data_wdata_o,
  input[31:0] data_rdata_i,
  input data_err_i,
  input debug_req_i,
  input fetch_enable_i,
  output core_busy_o
);
endmodule
